name: Grab Top 50 tiktok/youtube info

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl "https://api-yt-est.livecounts.lol/top50_tiktok/live?akey=API-_key-8UCD7P7h0IjG3rF9dfJ7ahY6pnVJOhnTFaAqogmKg&skey=KarFC9A5zo8LMBDyiCgzEJQMG3X5ermp43o4cjHwarAn50" | jq . > top50_tiktok.json
        curl "https://api-yt-est.livecounts.lol/top50_youtube/private/live" | jq . > top50_youtube.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
